Update cd.md
cloud-native-toolkit/developer-guide pull request #479
Opened 2021-08-18 12:47 UTC by rogerxaic

OpenShift Operator-deployed ArgoCD does no longer feature a "Log in with OpenShift" button. Here are instructions on how to retrieve the `admin` password and how to use it to log in to ArgoCD.

2021-08-18 13:55 UTC, lsteck commented
Hi @rogerxaic 

Thanks for the update but I think it would be easier to run the `oc credentials` command to get the ArgoCD admin password.  Could you update your changes to use that command?  Thanks!

2021-08-19 02:53 UTC, csantanapr commented on docs/resources/workshop/cd.md
> +    - Get ArgoCD's `admin` password by running `oc extract secrets/openshift-gitops-cluster --keys=admin.password -n openshift-gitops --to=-`
The password is two different places depending OCP46 or OCP47+

OCP46: `secrets/argocd-cluster-cluster`
OCP47: `secrets/openshift-gitops-cluster`

We are making fixes to have it easier for the user to just run `oc credentials`
WIth OCP48 the OpenShift SSO would be fix and user can just click the "Login with OpenShift"

2021-08-19 03:05 UTC, csantanapr requested changes
Thanks for @rogerxaic for the PR.
I was able to fix argocd on OCP47 here is the final fix https://github.com/cloud-native-toolkit/ibm-garage-iteration-zero/pull/355

Please update the text to tell the user to use `oc credentials` to get the password

2021-08-19 14:13 UTC, lsteck reviewed
LGTM

2021-08-19 14:20 UTC, csantanapr approved these changes

2021-08-19 14:20 UTC, merged